### ISSUE TITLE
Error in starting ./pipeline.sh

### ISSUE THREAD

**Issue by altezza04** [AaronWard/coronavirus-analysis#1]
Not sure what happened. thanks!

Traceback (most recent call last):
  File "./src/data_prep.py", line 79, in <module>
    cleaned_ranges = clean_sheet_names(sheets)
  File "./src/data_prep.py", line 27, in clean_sheet_names
    clean_new_ranges = new_ranges.copy()
AttributeError: 'list' object has no attribute 'copy'
###
###
Traceback (most recent call last):
  File "./src/data_exploration.py", line 13, in <module>
    plt.style.use('ggplot')
AttributeError: 'module' object has no attribute 'style'

**Comment by AaronWard** [comment]
@altezza04 can you check which versions of pandas and matplotlib you have with a pip freeze?

**Comment by AaronWard** [comment]
@altezza04 Made some changed to the code and added a `requirements.txt` and works okay on my end, if the problem persists then it must be a dependency issue. 

Here is the version i have:
```
matplotlib==3.1.0
google-api-python-client==1.7.11
google-auth==1.11.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-pasta==0.1.7
pyarrow==0.15.1
pandas==0.25.3
```
