### ISSUE TITLE
ImportError: No module named docopt

### ISSUE THREAD

**Issue by iccupwin** [AaronWard/coronavirus-analysis#47]
When I running it gives an error. **ImportError: No module named docopt**.   although I have installed

![zxcxzc](https://user-images.githubusercontent.com/35561658/89331271-45fe3880-d6b3-11ea-9e61-8c56be299fdf.png)

**Comment by AaronWard** [comment]
Strange, it's in the `requirements.txt` so it should install automatically.
Are you using a conda environment? 

If not i would suggest creating one and install  **`covidify`** again, if this doesn't work let me know

**Comment by AaronWard** [comment]
Closing because inactivity
